# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=400, null=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('labels', models.ManyToManyField(blank=True, related_name='emails', to='mail_server.Label')),
                ('template', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_server.Template')),
            ],
        ),
    ]
