# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_server', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='family_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
