# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_server', '0003_email_family_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='thread_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
